module.exports = [
  {
    $id: 1,
    title: "V-Neck Tee",
    keywords: ["v-necks", "v-neck t-shirts", "v-neck tees", "tees", "t-shirts"],
    price: { value: 14.95, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "TommyHilfiger",
    gender: "Male",
    style: "Tee",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "100% Cotton. Imported. Machine Wash. Embroidered flag logo at chest. Rib neck trim. Classic fit. Short sleeve. Fabric content for heathered color ways is 60 percent cotton, 40 percent polyester.",
    images: [{url:'/images/V-Neck-Male.jpg'}],
  },
  {
    $id: 2,
    title: "Polo Shirt",
    keywords: ["polo shirts", "polos"],
    price: { value: 19, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "TommyHilfiger",
    gender: "Male",
    style: "Polo",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "Tommy Hilfiger Men's Custom Fit Polo Shirt. Two button placket. Ribbed collar and armbands Heritage Flag Logo on Left Chest. 100 cotton. Machine washable. Imported.",
    images: [{url:'/images/Polo-Shirt-Male.jpg'}],
  },
  {
    $id: 3,
    title: "Collar Dress Shirt",
    keywords: ["collar dress shirts", "dress shirts"],
    price: { value: 53.95, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "TommyHilfiger",
    gender: "Male",
    style: "DressShirt",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "100% Cotton. Imported. Machine Wash. Spread collar. Regular cuff. Pocket at chest.",
    images: [{url:'/images/Collar-Dress-Shirt-Male.jpg'}],
  },
  {
    $id: 4,
    title: "Crew Neck Sweatshirt",
    keywords: ["crew necks", "crew neck sweatshirts", "sweatshirts"],
    price: { value: 53.95, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "TommyHilfiger",
    gender: "Female",
    style: "Sweatshirt",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "90% Cotton, 10% Polyester. Embroidered heritage logo accents left chest. Ribbed crew neck, cuffs and waist. Contrast long sleeves. Machine wash",
    images: [{ url:'/images/Crew-Neck-Sweatshirt-Female.jpg'}],
  },
  {
    $id: 5,
    title: "Cotton Henley Tank",
    keywords: ["henleys", "cotton henley tanks", "cotton henleys", "henly tanks", "tanks"],
    price: { value: 22.69, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "TommyHilfiger",
    gender: "Female",
    style: "Henley",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "95% Cotton/5% Spandex. Pull On closure. Machine Wash. A basics essential from Tommy Hilfiger knit pajama pant with logo waistband and working draw tie. A perfect combination of comfort and quality. Relaxed-fitting sleep pant featuring logoed elastic waistband with drawstring",
    images: [{url:'/images/Cotton-Henley-Tank-Female.jpg'}],
  },
  {
    $id: 6,
    title: "Pony Logo T-Shirt",
    keywords: ["pony logo shirts", "pony logo t-shirts", "pony logo tees", "tees"],
    price: { value: 26, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "RalphLauren",
    gender: "Male",
    style: "Tee",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "Polo Ralph Lauren Men's Crew Neck T-shirt. Crew neckline.Short sleeves.Classic fit. Embroidered pony accents left chest. 100% cotton. Machine washable. Imported.",
    images: [{url:'/images/Pony-Logo-T-Shirt-Male.jpg'}],
  },
  {
    $id: 7,
    title: "Oxford Dress Shirt",
    keywords: ["dress shirts", "oxford dress shirts", "oxford dress", "oxford shirts"],
    price: { value: 26, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "RalphLauren",
    gender: "Male",
    style: "DressShirt",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "100% Cotton. Imported. Machine washable. Ralph Lauren Men Button Down Dress Shirt. Applied buttoned placket. Embroidered pony accents the left chest. Cotton. Machine washable.Imported.",
    images: [{url:'/images/Oxford-Dress-Shirt-Male.jpg'}],
  },
  {
    $id: 8,
    title: "Pullover Sweatshirt",
    keywords: ["sweatshirts", "pullovers", "pullover sweatshirts"],
    price: { value: 24.80, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "RalphLauren",
    gender: "Female",
    style: "Sweatshirt",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "Polo Ralph Lauren. Split, vented hem. Kangaroo Pocket. Features The Signature Embroidered Pony Logo. Machine Washable.",
    images: [{url:'/images/Pullover-Sweatshirt-Female.jpg'}],
  },
  {
    $id: 9,
    title: "Striped Cotton Henley Top",
    keywords: ["henleys", "henley tops", "striped cotton heley tops", "striped cotton tops", "striped cotton henleys", "striped heleys", "striped henley tops"],
    price: { value: 34.95, currencyType: {currencyCode: "USD", prefixSymbol: "$"} },
    brand: "RalphLauren",
    gender: "Female",
    style: "Henley",
    availableSizes: ["ExtraSmall", "Small", "Medium", "Large", "ExtraLarge"],
    description: "100% Cotton. Striped. Cotton. Broadcloth. China",
    images: [{url:'/images/Striped-Cotton-Henley-Top-Female.jpg'}],
  },
]